install:
  - cd ./src
  - dotnet restore
image: Visual Studio 2019
branches:
  only:
    - master
deploy:
  provider: NuGet
  api_key:
    secure: tP1nLIkxWmW2verdbala1nUbzmphYTyV7KZ5zkmHUZfDRvj6QRkE6cUiLeLHysTB